Set-Variable Debug -Value $true -Scope Global -Option ReadOnly -Force
Set-Variable Port -Value 8080 -Scope Global -Option ReadOnly -Force
Set-Variable Url -Value "http://localhost" -Scope Global -Option ReadOnly -Force
Set-Variable DefaultGroupPrefix -Value "" -Scope Global -Option ReadOnly -Force
Set-Variable DefaultGroupEndPoint -Value "/" -Scope Global -Option ReadOnly -Force
Set-Variable Template -Value "" -Scope Global -Option ReadOnly -Force
Set-Variable ServeStaticFiles -Value $false -Scope Global -Option ReadOnly -Force
Set-Variable StaticFilesPath -Value "" -Scope Global -Option ReadOnly -Force
Set-Variable ProjectName -Value "Rocket" -Scope Global -Option ReadOnly -Force