#
# Module manifest for module 'Rocket'
#
# Generated by: Ariadne Rangel
#
# Generated on: 10/4/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Rocket.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'dadea276-ae04-4c01-b901-06838167ec7c'

# Author of this module
Author = 'Ariadne Rangel'

# Company or vendor of this module
CompanyName = 'Ariadne Rangel'

# Copyright statement for this module
Copyright = '(c) 2024 Ariadne Rangel. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Rocket is a minimalist web framework for PowerShell'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Use-Rocket', 'Use-RocketGui'

# Cmdlets to export from this module, for best performanc   e, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("web-framework", "web-server", "http-server", "http-listener", "micro-framework", "minimalist-framework")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/AriDevK/Rocket-PS/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/AriDevK/Rocket-PS'

        # External dependent modules of this module
        ExternalModuleDependencies = @("eps")

    } # End of PSData hashtable

} # End of PrivateData hashtable

}

